
package com.carservice.project.wzcx;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TmriOutAccessPortType", targetNamespace = "http://webServices.service.dahong.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TmriOutAccessPortType {


    /**
     * 
     * @param xtlb
     * @param jkxlh
     * @param jkid
     * @param writeXmlDoc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:writeObjectOut")
    @WebResult(targetNamespace = "http://webServices.service.dahong.com")
    @RequestWrapper(localName = "writeObjectOut", targetNamespace = "http://webServices.service.dahong.com", className = "wzcx.WriteObjectOut")
    @ResponseWrapper(localName = "writeObjectOutResponse", targetNamespace = "http://webServices.service.dahong.com", className = "wzcx.WriteObjectOutResponse")
    public String writeObjectOut(
            @WebParam(name = "xtlb", targetNamespace = "http://webServices.service.dahong.com")
                    String xtlb,
            @WebParam(name = "jkxlh", targetNamespace = "http://webServices.service.dahong.com")
                    String jkxlh,
            @WebParam(name = "jkid", targetNamespace = "http://webServices.service.dahong.com")
                    String jkid,
            @WebParam(name = "WriteXmlDoc", targetNamespace = "http://webServices.service.dahong.com")
                    String writeXmlDoc);

    /**
     *
     * @param queryXmlDoc
     * @param xtlb
     * @param jkxlh
     * @param jkid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:queryObjectOut")
    @WebResult(targetNamespace = "http://webServices.service.dahong.com")
    @RequestWrapper(localName = "queryObjectOut", targetNamespace = "http://webServices.service.dahong.com", className = "wzcx.QueryObjectOut")
    @ResponseWrapper(localName = "queryObjectOutResponse", targetNamespace = "http://webServices.service.dahong.com", className = "wzcx.QueryObjectOutResponse")
    public String queryObjectOut(
            @WebParam(name = "xtlb", targetNamespace = "http://webServices.service.dahong.com")
                    String xtlb,
            @WebParam(name = "jkxlh", targetNamespace = "http://webServices.service.dahong.com")
                    String jkxlh,
            @WebParam(name = "jkid", targetNamespace = "http://webServices.service.dahong.com")
                    String jkid,
            @WebParam(name = "QueryXmlDoc", targetNamespace = "http://webServices.service.dahong.com")
                    String queryXmlDoc);

}
